datasets:
#  #tabular datasets
#  iris:
#    type: sklearn
#    data_type: tabular
#    filename: iris.csv
#    target: species
#    description: The Iris dataset with flower measurements
#  
#  wine:
#    type: sklearn
#    data_type: tabular
#    filename: wine.csv
#    target: target
#    description: Wine classification dataset
#
  boston_housing:
    type: url
    data_type: tabular
    filename: boston_housing.csv
    description: Boston housing prices dataset
    target: medv
    url: https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv
#
#
#  # image datasets
#  mnist:
#    type: torchvision
#    data_type: image
#    filename: mnist.pt
#    description: Handwritten digits dataset (28x28 grayscale images)
#  
#  fashion_mnist:
#    type: torchvision
#    data_type: image
#    filename: fashion_mnist.pt
#    description: Fashion articles dataset (28x28 grayscale images)
#  
#  cifar10:
#    type: torchvision
#    data_type: image
#    filename: cifar10.pt
#    description: Small color image classification dataset (32x32 color images)
#
#
#  # Time series datasets
#  electricity:
#    type: url
#    data_type: time_series
#    filename: electricity.zip
#    description: Electricity load diagrams dataset
#    url: https://archive.ics.uci.edu/ml/machine-learning-databases/00321/LD2011_2014.txt.zip
#    extract: true
#
#  # Text datasets
#  imdb_reviews:
#    type: url
#    data_type: text
#    filename: imdb_reviews.tar.gz
#    description: IMDB movie reviews sentiment dataset
#    url: https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
#    extract: true